package sk.upjs.ics.novotnyr.bookr.gui;

import sk.upjs.ics.novotnyr.bookr.*;

import javax.swing.*;
import javax.swing.table.AbstractTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;

public class BookDetailForm {
    private CommentDao commentDao = BeanFactory.INSTANCE.commentDao();
    private BookDao bookDao = BeanFactory.INSTANCE.bookDao();

    private JPanel panel;
    private JLabel lblTitle;
    private JLabel lblPublisher;
    private JLabel lblYear;
    private JButton btnComments;
    private JLabel lblRating;
    private JTable tblComments;
    private JTextField txtComment;
    private JButton btnAddComment;
    private JComboBox cbxRating;
    private JDialog dialog;

    private Book book;
    private MyTableModel myTableModel;

    public BookDetailForm(Book book) {

        this.book = book;
        dialog = new JDialog(GuiFactory.INSTANCE.bookDashboardForm(), "Book detail", true);

        myTableModel = new MyTableModel(book.getComments());
        tblComments.setModel(myTableModel);
        tblComments.setComponentPopupMenu(createTblCommentPopupMenu());
        tblComments.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        refresh();

        btnAddComment.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                btnAddCommentActionPerformed(e);
            }
        });

        dialog.add(panel);
        dialog.setSize(640, 480);
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    }

    private JPopupMenu createTblCommentPopupMenu() {

        JPopupMenu popupMenu = new JPopupMenu();
        popupMenu.add(new AbstractAction("Delete") {
            @Override
            public void actionPerformed(ActionEvent e) {
                popupTblCommentsDeleteActionPerformed(e);
            }
        });
        return popupMenu;
    }

    private void popupTblCommentsDeleteActionPerformed(ActionEvent e) {
        Comment selectedComment = (Comment) tblComments.getValueAt(tblComments.getSelectedRow(), -1);
        if (selectedComment != null) {
            int result = DialogUtils.yesNoDialog(dialog,
                    "The comment will be deleted! "
                            + selectedComment.getComment());
            if (result == JOptionPane.YES_OPTION) {
                commentDao.delete(selectedComment);
            }
        }

        refresh();
        GuiFactory.INSTANCE.bookDashboardForm().refreshBookData();
    }

    private void refresh() {
        book = bookDao.findById(book.getId());
        lblTitle.setText(book.getTitle());
        lblPublisher.setText(book.getPublisher().getName());
        lblYear.setText(Integer.toString(book.getYear()));
        lblRating.setText("Rating: " + book.getRating());

        MyTableModel myTableModel = (MyTableModel) tblComments.getModel();
        myTableModel.setComments(book.getComments());
    }

    private void btnAddCommentActionPerformed(ActionEvent e) {
        if (txtComment.getText().equals(""))
            return;
        Comment newComment = new Comment();
        newComment.setComment(txtComment.getText());
        newComment.setRating(cbxRating.getSelectedIndex() + 1);
        newComment.setBook(book);
        commentDao.saveOrUpdate(newComment);
        txtComment.setText("");
        cbxRating.setSelectedIndex(0);

        refresh();
        GuiFactory.INSTANCE.bookDashboardForm().refreshBookData();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(6, 6, new Insets(5, 5, 5, 5), -1, -1));
        lblTitle = new JLabel();
        lblTitle.setFont(new Font(lblTitle.getFont().getName(), Font.BOLD | Font.ITALIC, 20));
        lblTitle.setText("Choose a book");
        panel.add(lblTitle, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 5, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setText("Publisher:");
        panel.add(label1, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_EAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(62, 16), null, 0, false));
        lblPublisher = new JLabel();
        lblPublisher.setText("-");
        panel.add(lblPublisher, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(181, 16), null, 0, false));
        lblRating = new JLabel();
        lblRating.setFont(new Font(lblRating.getFont().getName(), Font.ITALIC, 18));
        lblRating.setText("-");
        panel.add(lblRating, new com.intellij.uiDesigner.core.GridConstraints(0, 5, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_EAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("Year:");
        panel.add(label2, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_EAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(62, 16), null, 0, false));
        lblYear = new JLabel();
        lblYear.setText("-");
        panel.add(lblYear, new com.intellij.uiDesigner.core.GridConstraints(2, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(181, 16), null, 0, false));
        final com.intellij.uiDesigner.core.Spacer spacer1 = new com.intellij.uiDesigner.core.Spacer();
        panel.add(spacer1, new com.intellij.uiDesigner.core.GridConstraints(1, 4, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final JScrollPane scrollPane1 = new JScrollPane();
        panel.add(scrollPane1, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 6, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        tblComments = new JTable();
        scrollPane1.setViewportView(tblComments);
        final com.intellij.uiDesigner.core.Spacer spacer2 = new com.intellij.uiDesigner.core.Spacer();
        panel.add(spacer2, new com.intellij.uiDesigner.core.GridConstraints(2, 4, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setFont(new Font(label3.getFont().getName(), Font.BOLD | Font.ITALIC, 18));
        label3.setText("Add new comment");
        panel.add(label3, new com.intellij.uiDesigner.core.GridConstraints(4, 0, 1, 6, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label4 = new JLabel();
        label4.setText("Comment:");
        panel.add(label4, new com.intellij.uiDesigner.core.GridConstraints(5, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtComment = new JTextField();
        panel.add(txtComment, new com.intellij.uiDesigner.core.GridConstraints(5, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(181, 24), null, 0, false));
        final JLabel label5 = new JLabel();
        label5.setText("Rating:");
        panel.add(label5, new com.intellij.uiDesigner.core.GridConstraints(5, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        cbxRating = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("1 - poor");
        defaultComboBoxModel1.addElement("2");
        defaultComboBoxModel1.addElement("3");
        defaultComboBoxModel1.addElement("4");
        defaultComboBoxModel1.addElement("5 - excelent");
        cbxRating.setModel(defaultComboBoxModel1);
        panel.add(cbxRating, new com.intellij.uiDesigner.core.GridConstraints(5, 3, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnAddComment = new JButton();
        btnAddComment.setText("Add");
        btnAddComment.setMnemonic('A');
        btnAddComment.setDisplayedMnemonicIndex(0);
        panel.add(btnAddComment, new com.intellij.uiDesigner.core.GridConstraints(5, 4, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        label4.setLabelFor(txtComment);
        label5.setLabelFor(cbxRating);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }

    private class MyTableModel extends AbstractTableModel {

        private List<Comment> comments;

        public MyTableModel(List<Comment> comments) {
            this.comments = comments;
        }

        public void setComments(List<Comment> comments) {
            this.comments = comments;
            fireTableDataChanged();
        }

        @Override
        public int getRowCount() {
            return comments.size();
        }

        @Override
        public int getColumnCount() {
            return 2;
        }

        @Override
        public String getColumnName(int column) {
            switch (column) {
                case 0:
                    return "Comment";
                case 1:
                    return "Rating";
            }
            return super.getColumnName(column);
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            Comment comment = comments.get(rowIndex);
            switch (columnIndex) {
                case -1:
                    return comment;
                case 0:
                    return comment.getComment();
                case 1:
                    return comment.getRating();
            }
            return "";
        }
    }
}
